trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  wwwrootdir: 'Tailspin.Spacegame.Web/webroot'
  dotnetsdkversion: '3.1.100'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.100'
  inputs:
    packageType: sdk
    version: $(dotnetsdkversion)

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'
- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artificat: drop'
  condition: succeeded()
